version: 2
jobs:
  build:
    docker:
    - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
    - checkout

    - run:
        name: Install Dependencies
        command: |
          python3 -m venv venv
          . venv/bin/activate

    - run:
        name: install AWSCLI
        command: sudo pip install awscli

    - run:
        name: zip the artifact
        command: |
          zip index.zip index.js

    - run:
        name: Upload lambda to  code deploy S3
        command: |
          aws s3 cp index.zip s3://${BUCKET}

    - run:
        name: update the lambda
        command: |
          aws lambda update-function-code --function-name csye6225 --region us-east-1 --zip-file fileb://index.zip